[project]
name = "railway-track-defect-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.0.1",
    "kaggle>=1.7.4.5",
    "matplotlib>=3.10.8",
    "opencv-python-headless>=4.13.0.92",
    "scikit-learn>=1.8.0",
    "streamlit>=1.55.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "wandb>=0.25.0",
    "zenml[local]>=0.93.3",
]
